{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 17,
   "id": "c988cab5-12f5-48dc-9513-85e1f77f7847",
   "metadata": {},
   "outputs": [],
   "source": [
    "import numpy as np\n",
    "import pandas as pd\n",
    "import seaborn as sns\n",
    "import matplotlib.pyplot as plt\n",
    "\n",
    "from sklearn.preprocessing import StandardScaler\n",
    "from sklearn.model_selection import train_test_split\n",
    "\n",
    "from sklearn.linear_model import LinearRegression\n",
    "\n",
    "from sklearn.metrics import mean_squared_error\n",
    "import numpy as np\n",
    "import pandas as pd\n",
    "import streamlit as st\n",
    "import joblib\n",
    "import warnings\n",
    "warnings.filterwarnings('ignore')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 18,
   "id": "713494e6-9ae2-4e29-abd8-e96fe2f6a935",
   "metadata": {},
   "outputs": [],
   "source": [
    "data = pd.read_csv('NVD.csv')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 19,
   "id": "2413d927-8f0e-41a5-a6d3-6e183ed4137a",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>cve/id</th>\n",
       "      <th>cve/sourceIdentifier</th>\n",
       "      <th>cve/published</th>\n",
       "      <th>cve/lastModified</th>\n",
       "      <th>cve/vulnStatus</th>\n",
       "      <th>cve/descriptions/0/lang</th>\n",
       "      <th>cve/descriptions/0/value</th>\n",
       "      <th>cve/descriptions/1/lang</th>\n",
       "      <th>cve/descriptions/1/value</th>\n",
       "      <th>cve/metrics/cvssMetricV2/0/source</th>\n",
       "      <th>...</th>\n",
       "      <th>cve/configurations/0/nodes/1/cpeMatch/7/vulnerable</th>\n",
       "      <th>cve/configurations/0/nodes/1/cpeMatch/7/criteria</th>\n",
       "      <th>cve/configurations/0/nodes/1/cpeMatch/7/matchCriteriaId</th>\n",
       "      <th>cve/references/0/tags/5</th>\n",
       "      <th>cve/configurations/0/nodes/0/cpeMatch/46/vulnerable</th>\n",
       "      <th>cve/configurations/0/nodes/0/cpeMatch/46/criteria</th>\n",
       "      <th>cve/configurations/0/nodes/0/cpeMatch/46/matchCriteriaId</th>\n",
       "      <th>cve/configurations/0/nodes/0/cpeMatch/47/vulnerable</th>\n",
       "      <th>cve/configurations/0/nodes/0/cpeMatch/47/criteria</th>\n",
       "      <th>cve/configurations/0/nodes/0/cpeMatch/47/matchCriteriaId</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>CVE-1999-0095</td>\n",
       "      <td>cve@mitre.org</td>\n",
       "      <td>1988-10-01T04:00:00.000</td>\n",
       "      <td>2019-06-11T20:29:00.263</td>\n",
       "      <td>Modified</td>\n",
       "      <td>en</td>\n",
       "      <td>The debug command in Sendmail is enabled, allo...</td>\n",
       "      <td>es</td>\n",
       "      <td>El comando de depuración de Sendmail está acti...</td>\n",
       "      <td>nvd@nist.gov</td>\n",
       "      <td>...</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>CVE-1999-0082</td>\n",
       "      <td>cve@mitre.org</td>\n",
       "      <td>1988-11-11T05:00:00.000</td>\n",
       "      <td>2008-09-09T12:33:40.853</td>\n",
       "      <td>Analyzed</td>\n",
       "      <td>en</td>\n",
       "      <td>CWD ~root command in ftpd allows root access.</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>nvd@nist.gov</td>\n",
       "      <td>...</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>CVE-1999-1471</td>\n",
       "      <td>cve@mitre.org</td>\n",
       "      <td>1989-01-01T05:00:00.000</td>\n",
       "      <td>2008-09-05T20:19:36.257</td>\n",
       "      <td>Analyzed</td>\n",
       "      <td>en</td>\n",
       "      <td>Buffer overflow in passwd in BSD based operati...</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>nvd@nist.gov</td>\n",
       "      <td>...</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>CVE-1999-1122</td>\n",
       "      <td>cve@mitre.org</td>\n",
       "      <td>1989-07-26T04:00:00.000</td>\n",
       "      <td>2018-05-03T01:29:04.817</td>\n",
       "      <td>Modified</td>\n",
       "      <td>en</td>\n",
       "      <td>Vulnerability in restore in SunOS 4.0.3 and ea...</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>nvd@nist.gov</td>\n",
       "      <td>...</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>CVE-1999-1467</td>\n",
       "      <td>cve@mitre.org</td>\n",
       "      <td>1989-10-26T04:00:00.000</td>\n",
       "      <td>2017-12-19T02:29:08.393</td>\n",
       "      <td>Modified</td>\n",
       "      <td>en</td>\n",
       "      <td>Vulnerability in rcp on SunOS 4.0.x allows rem...</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>nvd@nist.gov</td>\n",
       "      <td>...</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>...</th>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1995</th>\n",
       "      <td>CVE-2000-0462</td>\n",
       "      <td>cve@mitre.org</td>\n",
       "      <td>2000-05-28T04:00:00.000</td>\n",
       "      <td>2008-09-10T19:04:43.680</td>\n",
       "      <td>Analyzed</td>\n",
       "      <td>en</td>\n",
       "      <td>ftpd in NetBSD 1.4.2 does not properly parse e...</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>nvd@nist.gov</td>\n",
       "      <td>...</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1996</th>\n",
       "      <td>CVE-2000-0454</td>\n",
       "      <td>cve@mitre.org</td>\n",
       "      <td>2000-05-29T04:00:00.000</td>\n",
       "      <td>2008-09-10T19:04:43.087</td>\n",
       "      <td>Analyzed</td>\n",
       "      <td>en</td>\n",
       "      <td>Buffer overflow in Linux cdrecord allows local...</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>nvd@nist.gov</td>\n",
       "      <td>...</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1997</th>\n",
       "      <td>CVE-2000-0455</td>\n",
       "      <td>cve@mitre.org</td>\n",
       "      <td>2000-05-29T04:00:00.000</td>\n",
       "      <td>2008-09-10T19:04:43.147</td>\n",
       "      <td>Analyzed</td>\n",
       "      <td>en</td>\n",
       "      <td>Buffer overflow in xlockmore xlock program ver...</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>nvd@nist.gov</td>\n",
       "      <td>...</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1998</th>\n",
       "      <td>CVE-2000-0461</td>\n",
       "      <td>cve@mitre.org</td>\n",
       "      <td>2000-05-29T04:00:00.000</td>\n",
       "      <td>2008-09-10T19:04:43.587</td>\n",
       "      <td>Analyzed</td>\n",
       "      <td>en</td>\n",
       "      <td>The undocumented semconfig system call in BSD ...</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>nvd@nist.gov</td>\n",
       "      <td>...</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1999</th>\n",
       "      <td>CVE-2000-0564</td>\n",
       "      <td>cve@mitre.org</td>\n",
       "      <td>2000-05-29T04:00:00.000</td>\n",
       "      <td>2008-09-10T19:05:03.040</td>\n",
       "      <td>Analyzed</td>\n",
       "      <td>en</td>\n",
       "      <td>The guestbook CGI program in ICQ Web Front ser...</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>nvd@nist.gov</td>\n",
       "      <td>...</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>2000 rows × 442 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "             cve/id cve/sourceIdentifier            cve/published  \\\n",
       "0     CVE-1999-0095        cve@mitre.org  1988-10-01T04:00:00.000   \n",
       "1     CVE-1999-0082        cve@mitre.org  1988-11-11T05:00:00.000   \n",
       "2     CVE-1999-1471        cve@mitre.org  1989-01-01T05:00:00.000   \n",
       "3     CVE-1999-1122        cve@mitre.org  1989-07-26T04:00:00.000   \n",
       "4     CVE-1999-1467        cve@mitre.org  1989-10-26T04:00:00.000   \n",
       "...             ...                  ...                      ...   \n",
       "1995  CVE-2000-0462        cve@mitre.org  2000-05-28T04:00:00.000   \n",
       "1996  CVE-2000-0454        cve@mitre.org  2000-05-29T04:00:00.000   \n",
       "1997  CVE-2000-0455        cve@mitre.org  2000-05-29T04:00:00.000   \n",
       "1998  CVE-2000-0461        cve@mitre.org  2000-05-29T04:00:00.000   \n",
       "1999  CVE-2000-0564        cve@mitre.org  2000-05-29T04:00:00.000   \n",
       "\n",
       "             cve/lastModified cve/vulnStatus cve/descriptions/0/lang  \\\n",
       "0     2019-06-11T20:29:00.263       Modified                      en   \n",
       "1     2008-09-09T12:33:40.853       Analyzed                      en   \n",
       "2     2008-09-05T20:19:36.257       Analyzed                      en   \n",
       "3     2018-05-03T01:29:04.817       Modified                      en   \n",
       "4     2017-12-19T02:29:08.393       Modified                      en   \n",
       "...                       ...            ...                     ...   \n",
       "1995  2008-09-10T19:04:43.680       Analyzed                      en   \n",
       "1996  2008-09-10T19:04:43.087       Analyzed                      en   \n",
       "1997  2008-09-10T19:04:43.147       Analyzed                      en   \n",
       "1998  2008-09-10T19:04:43.587       Analyzed                      en   \n",
       "1999  2008-09-10T19:05:03.040       Analyzed                      en   \n",
       "\n",
       "                               cve/descriptions/0/value  \\\n",
       "0     The debug command in Sendmail is enabled, allo...   \n",
       "1         CWD ~root command in ftpd allows root access.   \n",
       "2     Buffer overflow in passwd in BSD based operati...   \n",
       "3     Vulnerability in restore in SunOS 4.0.3 and ea...   \n",
       "4     Vulnerability in rcp on SunOS 4.0.x allows rem...   \n",
       "...                                                 ...   \n",
       "1995  ftpd in NetBSD 1.4.2 does not properly parse e...   \n",
       "1996  Buffer overflow in Linux cdrecord allows local...   \n",
       "1997  Buffer overflow in xlockmore xlock program ver...   \n",
       "1998  The undocumented semconfig system call in BSD ...   \n",
       "1999  The guestbook CGI program in ICQ Web Front ser...   \n",
       "\n",
       "     cve/descriptions/1/lang  \\\n",
       "0                         es   \n",
       "1                        NaN   \n",
       "2                        NaN   \n",
       "3                        NaN   \n",
       "4                        NaN   \n",
       "...                      ...   \n",
       "1995                     NaN   \n",
       "1996                     NaN   \n",
       "1997                     NaN   \n",
       "1998                     NaN   \n",
       "1999                     NaN   \n",
       "\n",
       "                               cve/descriptions/1/value  \\\n",
       "0     El comando de depuración de Sendmail está acti...   \n",
       "1                                                   NaN   \n",
       "2                                                   NaN   \n",
       "3                                                   NaN   \n",
       "4                                                   NaN   \n",
       "...                                                 ...   \n",
       "1995                                                NaN   \n",
       "1996                                                NaN   \n",
       "1997                                                NaN   \n",
       "1998                                                NaN   \n",
       "1999                                                NaN   \n",
       "\n",
       "     cve/metrics/cvssMetricV2/0/source  ...  \\\n",
       "0                         nvd@nist.gov  ...   \n",
       "1                         nvd@nist.gov  ...   \n",
       "2                         nvd@nist.gov  ...   \n",
       "3                         nvd@nist.gov  ...   \n",
       "4                         nvd@nist.gov  ...   \n",
       "...                                ...  ...   \n",
       "1995                      nvd@nist.gov  ...   \n",
       "1996                      nvd@nist.gov  ...   \n",
       "1997                      nvd@nist.gov  ...   \n",
       "1998                      nvd@nist.gov  ...   \n",
       "1999                      nvd@nist.gov  ...   \n",
       "\n",
       "     cve/configurations/0/nodes/1/cpeMatch/7/vulnerable  \\\n",
       "0                                                   NaN   \n",
       "1                                                   NaN   \n",
       "2                                                   NaN   \n",
       "3                                                   NaN   \n",
       "4                                                   NaN   \n",
       "...                                                 ...   \n",
       "1995                                                NaN   \n",
       "1996                                                NaN   \n",
       "1997                                                NaN   \n",
       "1998                                                NaN   \n",
       "1999                                                NaN   \n",
       "\n",
       "      cve/configurations/0/nodes/1/cpeMatch/7/criteria  \\\n",
       "0                                                  NaN   \n",
       "1                                                  NaN   \n",
       "2                                                  NaN   \n",
       "3                                                  NaN   \n",
       "4                                                  NaN   \n",
       "...                                                ...   \n",
       "1995                                               NaN   \n",
       "1996                                               NaN   \n",
       "1997                                               NaN   \n",
       "1998                                               NaN   \n",
       "1999                                               NaN   \n",
       "\n",
       "     cve/configurations/0/nodes/1/cpeMatch/7/matchCriteriaId  \\\n",
       "0                                                   NaN        \n",
       "1                                                   NaN        \n",
       "2                                                   NaN        \n",
       "3                                                   NaN        \n",
       "4                                                   NaN        \n",
       "...                                                 ...        \n",
       "1995                                                NaN        \n",
       "1996                                                NaN        \n",
       "1997                                                NaN        \n",
       "1998                                                NaN        \n",
       "1999                                                NaN        \n",
       "\n",
       "     cve/references/0/tags/5  \\\n",
       "0                        NaN   \n",
       "1                        NaN   \n",
       "2                        NaN   \n",
       "3                        NaN   \n",
       "4                        NaN   \n",
       "...                      ...   \n",
       "1995                     NaN   \n",
       "1996                     NaN   \n",
       "1997                     NaN   \n",
       "1998                     NaN   \n",
       "1999                     NaN   \n",
       "\n",
       "     cve/configurations/0/nodes/0/cpeMatch/46/vulnerable  \\\n",
       "0                                                   NaN    \n",
       "1                                                   NaN    \n",
       "2                                                   NaN    \n",
       "3                                                   NaN    \n",
       "4                                                   NaN    \n",
       "...                                                 ...    \n",
       "1995                                                NaN    \n",
       "1996                                                NaN    \n",
       "1997                                                NaN    \n",
       "1998                                                NaN    \n",
       "1999                                                NaN    \n",
       "\n",
       "     cve/configurations/0/nodes/0/cpeMatch/46/criteria  \\\n",
       "0                                                  NaN   \n",
       "1                                                  NaN   \n",
       "2                                                  NaN   \n",
       "3                                                  NaN   \n",
       "4                                                  NaN   \n",
       "...                                                ...   \n",
       "1995                                               NaN   \n",
       "1996                                               NaN   \n",
       "1997                                               NaN   \n",
       "1998                                               NaN   \n",
       "1999                                               NaN   \n",
       "\n",
       "     cve/configurations/0/nodes/0/cpeMatch/46/matchCriteriaId  \\\n",
       "0                                                   NaN         \n",
       "1                                                   NaN         \n",
       "2                                                   NaN         \n",
       "3                                                   NaN         \n",
       "4                                                   NaN         \n",
       "...                                                 ...         \n",
       "1995                                                NaN         \n",
       "1996                                                NaN         \n",
       "1997                                                NaN         \n",
       "1998                                                NaN         \n",
       "1999                                                NaN         \n",
       "\n",
       "     cve/configurations/0/nodes/0/cpeMatch/47/vulnerable  \\\n",
       "0                                                   NaN    \n",
       "1                                                   NaN    \n",
       "2                                                   NaN    \n",
       "3                                                   NaN    \n",
       "4                                                   NaN    \n",
       "...                                                 ...    \n",
       "1995                                                NaN    \n",
       "1996                                                NaN    \n",
       "1997                                                NaN    \n",
       "1998                                                NaN    \n",
       "1999                                                NaN    \n",
       "\n",
       "     cve/configurations/0/nodes/0/cpeMatch/47/criteria  \\\n",
       "0                                                  NaN   \n",
       "1                                                  NaN   \n",
       "2                                                  NaN   \n",
       "3                                                  NaN   \n",
       "4                                                  NaN   \n",
       "...                                                ...   \n",
       "1995                                               NaN   \n",
       "1996                                               NaN   \n",
       "1997                                               NaN   \n",
       "1998                                               NaN   \n",
       "1999                                               NaN   \n",
       "\n",
       "      cve/configurations/0/nodes/0/cpeMatch/47/matchCriteriaId  \n",
       "0                                                   NaN         \n",
       "1                                                   NaN         \n",
       "2                                                   NaN         \n",
       "3                                                   NaN         \n",
       "4                                                   NaN         \n",
       "...                                                 ...         \n",
       "1995                                                NaN         \n",
       "1996                                                NaN         \n",
       "1997                                                NaN         \n",
       "1998                                                NaN         \n",
       "1999                                                NaN         \n",
       "\n",
       "[2000 rows x 442 columns]"
      ]
     },
     "execution_count": 19,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "data"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 20,
   "id": "54c49ff0-4278-4ac8-98b8-ed327e466016",
   "metadata": {},
   "outputs": [],
   "source": [
    "new_column_names = {\n",
    "    'cve/id': 'cve id',\n",
    "    'cve/sourceIdentifier': 'sourceIdentifier',\n",
    "    'cve/published': 'published',\n",
    "    'cve/lastModified': 'lastModified',\n",
    "    'cve/vulnStatus': 'Status',\n",
    "    # Add more column mappings as needed\n",
    "}"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 21,
   "id": "bdad0626-8b48-4529-ba80-2bd13df9e2ee",
   "metadata": {},
   "outputs": [],
   "source": [
    "data.rename(columns=new_column_names, inplace=True)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 22,
   "id": "cfdbcea8-9b2d-4505-b350-05b08136b076",
   "metadata": {},
   "outputs": [],
   "source": [
    "\n",
    "def read_first_5_records(input_file):\n",
    "    data = pd.read_csv(input_file)\n",
    "    \n",
    "    first_5_records = data.head(5)\n",
    "    return first_5_records\n",
    "    "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 23,
   "id": "6cd523f8-0865-4576-8c16-228c966fdd88",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2024-05-29 12:17:00.507 \n",
      "  \u001b[33m\u001b[1mWarning:\u001b[0m to view this Streamlit app on a browser, run it with the following\n",
      "  command:\n",
      "\n",
      "    streamlit run C:\\Users\\saiga\\anaconda3\\Lib\\site-packages\\ipykernel_launcher.py [ARGUMENTS]\n"
     ]
    }
   ],
   "source": [
    "def main():\n",
    "    st.title('NVD')\n",
    "    html_tmp = \"\"\"\n",
    "    <div style='background-color:red;'>\n",
    "    <h2 style='color:white;text-align:center;'>CVE LIST</h2>\n",
    "    </div>\n",
    "    \"\"\"\n",
    "    st.markdown(html_tmp, unsafe_allow_html=True)\n",
    "    st.write(\"First five rows\")\n",
    "    st.dataframe(data.head(5))\n",
    "\n",
    "if __name__ == '__main__':\n",
    "    main()\n",
    "\n",
    "    "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "6698c28b-8f7b-4599-8d80-b2c8e6793588",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
